// SPDX-FileCopyrightText: 2026 plasmaar contributors
// SPDX-License-Identifier: GPL-2.0-or-later

#include "plasmaarkcm.h"

#include "controller.h"

#include <KPluginFactory>

// Generated by qt_add_qml_module for the static io.github.fredaime.plasmaar module. Calling it also keeps
// the registration code from being dropped by the linker.
void qml_register_types_io_github_fredaime_plasmaar();

K_PLUGIN_CLASS_WITH_JSON(PlasmaarKcm, "kcm_plasmaar.json")

PlasmaarKcm::PlasmaarKcm(QObject *parent, const KPluginMetaData &metaData)
    : KQuickConfigModule(parent, metaData)
    , m_controller(new Controller(QDBusConnection::sessionBus(), this))
{
    static const bool qmlTypesRegistered = [] {
        qml_register_types_io_github_fredaime_plasmaar();
        return true;
    }();
    Q_UNUSED(qmlTypesRegistered)
    setButtons(Apply | Default);

    // Nothing is fetched before the host calls load(): it follows changes of representsDefaults only
    // once it has set the module up.
    connect(m_controller, &Controller::stagingChanged, this, &PlasmaarKcm::updateState);
}

Controller *PlasmaarKcm::controller() const
{
    return m_controller;
}

void PlasmaarKcm::updateState()
{
    setNeedsSave(m_controller->needsSave());
    // Without known defaults there is nothing to go back to: this disables the Defaults button.
    const bool atDefaults = !m_controller->hasDefaults() || m_controller->atDefaults();
    if (atDefaults == representsDefaults()) {
        Q_EMIT representsDefaultsChanged(); // the host may have missed the last change
    }
    setRepresentsDefaults(atDefaults);
}

void PlasmaarKcm::load()
{
    KQuickConfigModule::load();
    m_controller->load();
    updateState();
}

void PlasmaarKcm::save()
{
    KQuickConfigModule::save();
    m_controller->save();
    updateState();
}

void PlasmaarKcm::defaults()
{
    KQuickConfigModule::defaults();
    m_controller->defaults();
    updateState();
}

#include "plasmaarkcm.moc"
